Add id attribute to VictoryLabelProps interface
FormidableLabs/victory pull request #1800
Opened 2021-03-02 09:43 UTC by nielsboecker

As per https://github.com/FormidableLabs/victory/pull/1575 and https://github.com/FormidableLabs/victory-docs/pull/678, `VictoryLabel` can receive an`id` prop.

2021-03-03 23:37 UTC, boygirl requested changes
@nielsboecker Thanks for taking the time to address this. I think it would be cleaner with a minor change. Does that work for you?

2021-03-03 23:37 UTC, boygirl commented on packages/victory-core/src/index.d.ts
> +  id?: string | number | Function;
What about using `StringOrNumberOrCallback`?

2021-03-04 09:01 UTC, nielsboecker commented
Hi @boygirl, thanks for your quick response. :) Yes, great point, that's cleaner indeed.

2021-03-04 17:43 UTC, boygirl approved these changes

2021-03-04 17:43 UTC, boygirl commented
@nielsboecker thanks! I'll get a patch out for you today :)

2021-03-04 17:43 UTC, merged